### PR TITLE
Fix logging

### PR DESCRIPTION
**Pull request by XanderXAJ**
I noticed that logging wasn't working due to PR #10, so I endeavoured to fix it.  Turns out this wasn't quite as straightforward as I had hoped -- it seems permissions between a host and container remains a thorny issue in Docker.

The [suggested solution among the docker writers](http://container42.com/2013/12/16/persistent-volumes-with-docker-container-as-volume-pattern/) is to use a data-only container, which you'll note is another instance of the `teamspeak` container.  Don't worry, [it doesn't take up any extra space](http://container42.com/2014/11/18/data-only-container-madness/).  The approach has the positive of allowing us to sidestep the permissions issue (the TS container and TS data container share the same permissions), but has the negative of making data management a bit harder to reason with as we do not store data on the host's file system in an obvious manner.

To make data management easier, I've made `ts3-backup.sh` and `ts3-restore.sh`.  Thanks to `tar`'s policy of changing permissions to the current non-root user, we then don't have to worry about permissions.  I've also made `ts3-build.sh` and `ts3-run.sh` to help with building and setting up the containers.

I've renamed the containers to `teamspeak` and `teamspeak-data` to be succinct.

I also included some extra hardening of the permissions and login setup, since this was related to my changes.  Please refer to my commit messages for all the details.

Apologies for the extent of the changes and wall of text!

### CODE REVIEW

**Comment by XanderXAJ** [comment]
This probably fixes #11.

I can also create a PR to update to the latest TeamSpeak 3.0.12 (which includes URL and file type and name changes), but in my repo it currently relies on the changes in this PR. ^^;

**Comment by pjgranahan** [comment]
I was able to successfully access the server admin privilege key using this branch. The `ts3-build.sh` and `ts3-run.sh` files were very helpful and worked well for me.

**Comment by overshard** [comment]
I dislike the method of having a second container for data only. While this is a solution it isn't an elegant solution to the issue and I'm checking into other methods. If I can't figure out anything nicer we'll use this.

**Comment by psykzz** [comment]
I'm actually a :+1: for having a data container. Its pretty much the standard when running docker containers and the setup here is really well done.

**Comment by adamkdean** [comment]
Can confirm that data volume containers were the standard, but now docker volumes are.

**Comment by XanderXAJ** [comment]
The [documentation](https://docs.docker.com/engine/tutorials/dockervolumes/) still suggests that data-only containers are the safest way to go, but I'll be the first to admit that it doesn't seem the most simple solution -- that's why I wrote the scripts to hide the complexity!

Named volumes might be a better middle ground between simplicity and convenience, while hopefully avoiding the necessity of having to modify users/permissions on the host.  I'd like to see the teamspeak container "just run" without any kind of preparation whatsoever if possible, as is the docker way.

**Comment by XanderXAJ** [comment]
I've updated my fork to use named volumes.  Because working with named volumes is surprisingly similar to data-only containers, I've retained the management scripts (`ts3-run`, `ts3-backup`, `ts3-restore`) to keep things easy for users.

https://github.com/XanderXAJ/docker-teamspeak

Since this original project has gone in a different direction, by storing files on the host filesystem, I haven't prepared a PR.  That said, here are links to the relevant commits:

https://github.com/XanderXAJ/docker-teamspeak/commit/c2331d5eab1c6b9be5beeeb1e573473c45b08270
https://github.com/XanderXAJ/docker-teamspeak/commit/dbb9ee6f62eba2b28ea27927a7b28e5c17dd1884

I'll also close this PR, again as the direction taken is a different one.

**Pull request closed without merging**
